const styleElement = getComputedStyle(document.getElementById("contenu"));
const listeElt = document.createElement("ul");
const longueurElt = document.createElement("li");
longueurElt.textContent = "Longueur : " + styleElement.width;
const hauteurElt = document.createElement("li");
hauteurElt.textContent = "Hauteur : " + styleElement.height;
listeElt.appendChild(hauteurElt);
listeElt.appendChild(longueurElt);
document.getElementById("infos").appendChild(document.createTextNode("Informations sur l'élément"));
document.getElementById("infos").appendChild(listeElt);